-- Seed catalog data
-- DELETE FROM catalog; -- Commented out to prevent FK errors on production
-- DELETE FROM sqlite_sequence WHERE name="catalog"; -- Commented out to prevent FK errors on production

INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('nwt', 'nwt-d', 'nwt-n', 'nwt-z', 4, 2, 1, 'Bibler', 0);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andrebibler', 'andrebibler-d', 'andrebibler-n', 'andrebibler-z', 0, 0, 0, 'Bibler', 1);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('be', 'be-d', 'be-n', 'be-z', 0, 0, 0, 'Bøger', 2);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('bhs', 'bhs-d', 'bhs-n', 'bhs-z', 0, 4, 4, 'Bøger', 3);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('bt', 'bt-d', 'bt-n', 'bt-z', 0, 0, 0, 'Bøger', 4);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('cf', 'cf-d', 'cf-n', 'cf-z', 0, 2, 2, 'Bøger', 5);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('cl', 'cl-d', 'cl-n', 'cl-z', 0, 0, 0, 'Bøger', 6);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('ia', 'ia-d', 'ia-n', 'ia-z', 1, 0, 0, 'Bøger', 7);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('jy', 'jy-d', 'jy-n', 'jy-z', 1, 0, 1, 'Bøger', 8);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('kr', 'kr-d', 'kr-n', 'kr-z', 0, 0, 0, 'Bøger', 9);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lfb', 'lfb-d', 'lfb-n', 'lfb-z', 0, 0, 0, 'Bøger', 10);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lff', 'lff-d', 'lff-n', 'lff-z', 8, 2, 10, 'Bøger', 11);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lr', 'lr-d', 'lr-n', 'lr-z', 0, 0, 0, 'Bøger', 12);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lvs', 'lvs-d', 'lvs-n', 'lvs-z', 0, 0, 0, 'Bøger', 13);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('od', 'od-d', 'od-n', 'od-z', 3, 0, 1, 'Bøger', 14);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('rr', 'rr-d', 'rr-n', 'rr-z', 2, 0, 0, 'Bøger', 15);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('scl', 'scl-d', 'scl-n', 'scl-z', 0, 0, 0, 'Bøger', 16);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('sjj', 'sjj-d', 'sjj-n', 'sjj-z', 1, 0, 3, 'Bøger', 17);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('sjjls', 'sjjls-d', 'sjjls-n', 'sjjls-z', 0, 0, 0, 'Bøger', 18);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('yp1', 'yp1-d', 'yp1-n', 'yp1-z', 0, 0, 2, 'Bøger', 19);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('yp2', 'yp2-d', 'yp2-n', 'yp2-z', 0, 2, 1, 'Bøger', 20);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andrebøger1', 'andrebøger1-d', 'andrebøger1-n', 'andrebøger1-z', 2, 2, 2, 'Bøger', 21);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andrebøger2', 'andrebøger2-d', 'andrebøger2-n', 'andrebøger2-z', 0, 1, 1, 'Bøger', 22);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('ed', 'ed-d', 'ed-n', 'ed-z', 0, 0, 0, 'Brochurer', 23);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('fg', 'fg-d', 'fg-n', 'fg-z', 2, 19, 15, 'Brochurer', 24);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('hf', 'hf-d', 'hf-n', 'hf-z', 2, 2, 2, 'Brochurer', 25);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('hl', 'hl-d', 'hl-n', 'hl-z', 0, 0, 0, 'Brochurer', 26);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('jl', 'jl-d', 'jl-n', 'jl-z', 0, 11, 7, 'Brochurer', 27);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('la', 'la-d', 'la-n', 'la-z', 0, 0, 0, 'Brochurer', 28);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lc', 'lc-d', 'lc-n', 'lc-z', 11, 22, 4, 'Brochurer', 29);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lf', 'lf-d', 'lf-n', 'lf-z', 22, 28, 8, 'Brochurer', 30);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lffi', 'lffi-d', 'lffi-n', 'lffi-z', 47, 19, 3, 'Brochurer', 31);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('ll', 'll-d', 'll-n', 'll-z', 0, 8, 0, 'Brochurer', 32);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('lmd', 'lmd-d', 'lmd-n', 'lmd-z', 3, 0, 20, 'Brochurer', 33);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('mb', 'mb-d', 'mb-n', 'mb-z', 2, 4, 4, 'Brochurer', 34);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('rj', 'rj-d', 'rj-n', 'rj-z', 0, 6, 2, 'Brochurer', 35);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('rk', 'rk-d', 'rk-n', 'rk-z', 0, 0, 0, 'Brochurer', 36);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('th', 'th-d', 'th-n', 'th-z', 8, 2, 3, 'Brochurer', 37);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wfg', 'wfg-d', 'wfg-n', 'wfg-z', 0, 0, 0, 'Brochurer', 38);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('ypq', 'ypq-d', 'ypq-n', 'ypq-z', 0, 0, 0, 'Brochurer', 39);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andrebroch1', 'andrebroch1-d', 'andrebroch1-n', 'andrebroch1-z', 5, 5, 8, 'Brochurer', 40);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andrebroch2', 'andrebroch2-d', 'andrebroch2-n', 'andrebroch2-z', 0, 0, 0, 'Brochurer', 41);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andrebroch3', 'andrebroch3-d', 'andrebroch3-n', 'andrebroch3-z', 0, 0, 0, 'Brochurer', 42);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('yc', 'yc-d', 'yc-n', 'yc-z', 8, 3, 2, 'Brochurer', 43);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('sp', 'sp-d', 'sp-n', 'sp-z', 0, 0, 0, 'Brochurer', 44);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('jwcd1', 'jwcd1-d', 'jwcd1-n', 'jwcd1-z', 0, 550, 520, 'Formularer', 45);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('jwcd4', 'jwcd4-d', 'jwcd4-n', 'jwcd4-z', 0, 0, 0, 'Formularer', 46);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('jwcd9', 'jwcd9-d', 'jwcd9-n', 'jwcd9-z', 227, 385, 377, 'Formularer', 47);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('jwcd10', 'jwcd10-d', 'jwcd10-n', 'jwcd10-z', 770, 430, 0, 'Formularer', 48);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('S-4', 'S-4-d', 'S-4-n', 'S-4-z', 0, 0, 0, 'Formularer', 49);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('S-24', 'S-24-d', 'S-24-n', 'S-24-z', 0, 0, 0, 'Formularer', 50);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('inv', 'inv-d', 'inv-n', 'inv-z', 0, 0, 0, 'Foldere', 51);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-30', 'T-30-d', 'T-30-n', 'T-30-z', 0, 0, 0, 'Foldere', 52);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-31', 'T-31-d', 'T-31-n', 'T-31-z', 0, 0, 0, 'Foldere', 53);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-32', 'T-32-d', 'T-32-n', 'T-32-z', 0, 0, 0, 'Foldere', 54);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-33', 'T-33-d', 'T-33-n', 'T-33-z', 0, 0, 0, 'Foldere', 55);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-34', 'T-34-d', 'T-34-n', 'T-34-z', 0, 0, 0, 'Foldere', 56);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-35', 'T-35-d', 'T-35-n', 'T-35-z', 0, 0, 0, 'Foldere', 57);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-36', 'T-36-d', 'T-36-n', 'T-36-z', 0, 0, 0, 'Foldere', 58);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-37', 'T-37-d', 'T-37-n', 'T-37-z', 0, 0, 0, 'Foldere', 59);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-dth', 'T-dth-d', 'T-dth-n', 'T-dth-z', 0, 0, 0, 'Foldere', 60);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-fam', 'T-fam-d', 'T-fam-n', 'T-fam-z', 0, 0, 0, 'Foldere', 61);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-ftr', 'T-ftr-d', 'T-ftr-n', 'T-ftr-z', 0, 0, 0, 'Foldere', 62);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-god', 'T-god-d', 'T-god-n', 'T-god-z', 0, 0, 0, 'Foldere', 63);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-jss', 'T-jss-d', 'T-jss-n', 'T-jss-z', 0, 0, 0, 'Foldere', 64);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-kng', 'T-kng-d', 'T-kng-n', 'T-kng-z', 0, 0, 0, 'Foldere', 65);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-pry', 'T-pry-d', 'T-pry-n', 'T-pry-z', 0, 0, 0, 'Foldere', 66);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-rlg', 'T-rlg-d', 'T-rlg-n', 'T-rlg-z', 0, 0, 0, 'Foldere', 67);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('T-sfr', 'T-sfr-d', 'T-sfr-n', 'T-sfr-z', 0, 0, 0, 'Foldere', 68);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g18.1', 'g18.1-d', 'g18.1-n', 'g18.1-z', 0, 0, 0, 'Offentlige blade', 69);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g18.2', 'g18.2-d', 'g18.2-n', 'g18.2-z', 45, 20, 19, 'Offentlige blade', 70);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g18.3', 'g18.3-d', 'g18.3-n', 'g18.3-z', 39, 40, 39, 'Offentlige blade', 71);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g19.1', 'g19.1-d', 'g19.1-n', 'g19.1-z', 0, 0, 0, 'Offentlige blade', 72);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g19.2', 'g19.2-d', 'g19.2-n', 'g19.2-z', 0, 0, 0, 'Offentlige blade', 73);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g19.3', 'g19.3-d', 'g19.3-n', 'g19.3-z', 0, 0, 0, 'Offentlige blade', 74);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g20.1', 'g20.1-d', 'g20.1-n', 'g20.1-z', 44, 1, 38, 'Offentlige blade', 75);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g20.2', 'g20.2-d', 'g20.2-n', 'g20.2-z', 0, 0, 0, 'Offentlige blade', 76);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g20.3', 'g20.3-d', 'g20.3-n', 'g20.3-z', 0, 0, 0, 'Offentlige blade', 77);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g21.1', 'g21.1-d', 'g21.1-n', 'g21.1-z', 0, 0, 2, 'Offentlige blade', 78);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g21.2', 'g21.2-d', 'g21.2-n', 'g21.2-z', 20, 0, 1, 'Offentlige blade', 79);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g21.3', 'g21.3-d', 'g21.3-n', 'g21.3-z', 40, 2, 26, 'Offentlige blade', 80);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g22.1', 'g22.1-d', 'g22.1-n', 'g22.1-z', 27, 4, 13, 'Offentlige blade', 81);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g23.1', 'g23.1-d', 'g23.1-n', 'g23.1-z', 8, 26, 8, 'Offentlige blade', 82);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g24.1', 'g24.1-d', 'g24.1-n', 'g24.1-z', 23, 29, 18, 'Offentlige blade', 83);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('g25.1', 'g25.1-d', 'g25.1-n', 'g25.1-z', 30, 12, 32, 'Offentlige blade', 84);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp18.1', 'wp18.1-d', 'wp18.1-n', 'wp18.1-z', 0, 0, 0, 'Offentlige blade', 85);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp18.2', 'wp18.2-d', 'wp18.2-n', 'wp18.2-z', 12, 5, 0, 'Offentlige blade', 86);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp18.3', 'wp18.3-d', 'wp18.3-n', 'wp18.3-z', 34, 33, 40, 'Offentlige blade', 87);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp19.1', 'wp19.1-d', 'wp19.1-n', 'wp19.1-z', 29, 32, 26, 'Offentlige blade', 88);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp19.2', 'wp19.2-d', 'wp19.2-n', 'wp19.2-z', 0, 0, 0, 'Offentlige blade', 89);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp19.3', 'wp19.3-d', 'wp19.3-n', 'wp19.3-z', 0, 0, 0, 'Offentlige blade', 90);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp20.1', 'wp20.1-d', 'wp20.1-n', 'wp20.1-z', 0, 0, 0, 'Offentlige blade', 91);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp20.2', 'wp20.2-d', 'wp20.2-n', 'wp20.2-z', 22, 13, 20, 'Offentlige blade', 92);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp20.3', 'wp20.3-d', 'wp20.3-n', 'wp20.3-z', 0, 0, 0, 'Offentlige blade', 93);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp21.1', 'wp21.1-d', 'wp21.1-n', 'wp21.1-z', 38, 0, 28, 'Offentlige blade', 94);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp21.2', 'wp21.2-d', 'wp21.2-n', 'wp21.2-z', 345, 106, 318, 'Offentlige blade', 95);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp21.3', 'wp21.3-d', 'wp21.3-n', 'wp21.3-z', 8, 0, 16, 'Offentlige blade', 96);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp22.1', 'wp22.1-d', 'wp22.1-n', 'wp22.1-z', 29, 4, 11, 'Offentlige blade', 97);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp23.1', 'wp23.1-d', 'wp23.1-n', 'wp23.1-z', 4, 0, 0, 'Offentlige blade', 98);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp24.1', 'wp24.1-d', 'wp24.1-n', 'wp24.1-z', 0, 10, 1, 'Offentlige blade', 99);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('wp25.1', 'wp25.1-d', 'wp25.1-n', 'wp25.1-z', 0, 0, 0, 'Offentlige blade', 100);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andreblade1', 'andreblade1-d', 'andreblade1-n', 'andreblade1-z', 0, 0, 0, 'Offentlige blade', 101);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andreblade2', 'andreblade2-d', 'andreblade2-n', 'andreblade2-z', 0, 0, 0, 'Offentlige blade', 102);
INSERT OR IGNORE INTO catalog (code, name_da, name_no, name_sv, quantity_da, quantity_no, quantity_sv, section, sort_order) VALUES ('andreblade3', 'andreblade3-d', 'andreblade3-n', 'andreblade3-z', 0, 0, 0, 'Offentlige blade', 103);
